.PHONY: all client_to_broker client_to_rabbitmq client_to_kafka

all: client_to_broker client_to_rabbitmq client_to_kafka

client_to_broker:
	$(MAKE) -C client_to_broker

client_to_rabbitmq:
	$(MAKE) -C client_to_rabbitmq

client_to_kafka:
	$(MAKE) -C client_to_kafka