.PHONY: all nwpc_message_client nwpc_message_consumer

all: nwpc_message_client nwpc_message_consumer

nwpc_message_client:
	$(MAKE) -C nwpc_message_client

nwpc_message_consumer:
	$(MAKE) -C nwpc_message_consumer