// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messagebroker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MessageBrokerClient is the client API for MessageBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageBrokerClient interface {
	SendRabbitMQMessage(ctx context.Context, in *RabbitMQMessage, opts ...grpc.CallOption) (*Response, error)
	SendKafkaMessage(ctx context.Context, in *KafkaMessage, opts ...grpc.CallOption) (*Response, error)
}

type messageBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBrokerClient(cc grpc.ClientConnInterface) MessageBrokerClient {
	return &messageBrokerClient{cc}
}

func (c *messageBrokerClient) SendRabbitMQMessage(ctx context.Context, in *RabbitMQMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/messagebroker.MessageBroker/SendRabbitMQMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) SendKafkaMessage(ctx context.Context, in *KafkaMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/messagebroker.MessageBroker/SendKafkaMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBrokerServer is the server API for MessageBroker service.
// All implementations must embed UnimplementedMessageBrokerServer
// for forward compatibility
type MessageBrokerServer interface {
	SendRabbitMQMessage(context.Context, *RabbitMQMessage) (*Response, error)
	SendKafkaMessage(context.Context, *KafkaMessage) (*Response, error)
	mustEmbedUnimplementedMessageBrokerServer()
}

// UnimplementedMessageBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageBrokerServer struct {
}

func (UnimplementedMessageBrokerServer) SendRabbitMQMessage(context.Context, *RabbitMQMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRabbitMQMessage not implemented")
}
func (UnimplementedMessageBrokerServer) SendKafkaMessage(context.Context, *KafkaMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendKafkaMessage not implemented")
}
func (UnimplementedMessageBrokerServer) mustEmbedUnimplementedMessageBrokerServer() {}

// UnsafeMessageBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBrokerServer will
// result in compilation errors.
type UnsafeMessageBrokerServer interface {
	mustEmbedUnimplementedMessageBrokerServer()
}

func RegisterMessageBrokerServer(s grpc.ServiceRegistrar, srv MessageBrokerServer) {
	s.RegisterService(&_MessageBroker_serviceDesc, srv)
}

func _MessageBroker_SendRabbitMQMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RabbitMQMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).SendRabbitMQMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messagebroker.MessageBroker/SendRabbitMQMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).SendRabbitMQMessage(ctx, req.(*RabbitMQMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_SendKafkaMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KafkaMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).SendKafkaMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messagebroker.MessageBroker/SendKafkaMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).SendKafkaMessage(ctx, req.(*KafkaMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageBroker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messagebroker.MessageBroker",
	HandlerType: (*MessageBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRabbitMQMessage",
			Handler:    _MessageBroker_SendRabbitMQMessage_Handler,
		},
		{
			MethodName: "SendKafkaMessage",
			Handler:    _MessageBroker_SendKafkaMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_broker.proto",
}
